// Node-safe logical audio-id contract plus ?audio=1 gallery copy.
// Version/file resolution lives in audio-packs.js; playback stays in audio/music.

/** @type {{ id: string, group: string, use: string, note?: string, play?: 'sample'|'attack', attack?: { who: string, amount: number } }[]} */
export const SFX_CATALOG = [
  { id: 'click', group: 'UI', use: 'Buttons, menus, title / embark / vigil actions', note: 'stained-glass crystal tick' },
  { id: 'hover', group: 'UI', use: 'Card / option / lamplighter hover', note: 'quieter than click; rapid-safe' },
  { id: 'card', group: 'Cards', use: 'Card play motion, toss, discard/exhaust fidget, remove' },
  { id: 'draw', group: 'Cards', use: 'Draw-to-hand (staggered per card)' },
  { id: 'atkHeroLight', group: 'Attack', use: 'Hero hit, light (amount+blocked ≤ 5)', play: 'attack', attack: { who: 'hero', amount: 3 } },
  { id: 'atkHeroMed', group: 'Attack', use: 'Hero hit, medium (6–15)', play: 'attack', attack: { who: 'hero', amount: 10 } },
  { id: 'atkHeroHeavy', group: 'Attack', use: 'Hero hit, heavy (≥ 16)', play: 'attack', attack: { who: 'hero', amount: 20 } },
  { id: 'atkEnemyLight', group: 'Attack', use: 'Enemy hit on player, light (≤ 5)', play: 'attack', attack: { who: 'enemy', amount: 3 } },
  { id: 'atkEnemyMed', group: 'Attack', use: 'Enemy hit on player, medium (6–15)', play: 'attack', attack: { who: 'enemy', amount: 10 } },
  { id: 'atkEnemyHeavy', group: 'Attack', use: 'Enemy hit on player, heavy (≥ 16)', play: 'attack', attack: { who: 'enemy', amount: 20 } },
  { id: 'slash', group: 'Attack (legacy)', use: 'Routes to medium hero attack; sample kept for compatibility', note: 'Legacy' },
  { id: 'hit', group: 'Attack (legacy)', use: 'No-op wrapper; sample kept for compatibility', note: 'Legacy' },
  { id: 'blocked', group: 'Combat', use: 'Hit stopped by Ward / thorns / adamant', note: 'impact stopped ≠ block gain' },
  { id: 'block', group: 'Combat', use: 'Gain Ward', note: 'softer / more positive than blocked' },
  { id: 'poison', group: 'Combat', use: 'Smolder / poison apply or tick', note: 'ember-like Smolder, not swamp toxic' },
  { id: 'debuff', group: 'Combat', use: 'Debuff apply, burn/self damage, can’t-afford feedback' },
  { id: 'buff', group: 'Combat', use: 'Buff apply; power settle into glass' },
  { id: 'heal', group: 'Combat', use: 'Combat heal / rest heal feedback' },
  { id: 'energy', group: 'Combat', use: 'Energy gain event (candle pop)' },
  { id: 'coin', group: 'Meta', use: 'Gold pickup / shop spend / reward gold fly' },
  { id: 'potion', group: 'Meta', use: 'Use / gain phial' },
  { id: 'death', group: 'Combat', use: 'Normal enemy death', note: 'shatter family, smaller than shatter' },
  { id: 'bigDeath', group: 'Combat', use: 'Elite / boss death; also boss intro sting', note: 'shatter family, lower = bigger' },
  { id: 'turn', group: 'Combat', use: 'Your turn banner (turn > 1)' },
  { id: 'victory', group: 'Combat', use: 'Fight-won SFX sting (BGM victory is run-end only)' },
  { id: 'defeat', group: 'Combat', use: 'Fight-lost SFX sting (BGM defeat is run-end only)' },
  { id: 'relic', group: 'Meta', use: 'Relic gain / lamplighter confirm / unlock / monument' },
  { id: 'upgrade', group: 'Meta', use: 'Card upgrade at rest / forge / event / reward' },
  { id: 'map', group: 'Meta', use: 'Map enter / node travel one-shot (not map BGM)' },
  { id: 'chip', group: 'SHATTER', use: 'Facet chip tick' },
  { id: 'shatter', group: 'SHATTER', use: 'Shatter burst — brand signature' },
  { id: 'ember', group: 'SHATTER', use: 'Ember gain' },
  { id: 'kindle', group: 'SHATTER', use: 'Kindle / lantern feed' },
  { id: 'stagger', group: 'SHATTER', use: 'Enemy staggered' },
  { id: 'art', group: 'SHATTER', use: 'Lantern Art cast' },
  { id: 'omen', group: 'Meta', use: 'Omen banner / omen reveal on act entry' },
];

/** @type {{ id: string, title: string, use: string, wired: boolean }[]} */
export const MUSIC_CATALOG = [
  { id: 'title', title: 'Stained Glass Inscription', use: 'Title screen', wired: true },
  { id: 'embark', title: 'Light Your Lantern', use: 'Embark / Begin the Climb', wired: true },
  { id: 'vigil', title: 'Monuments in the Dark', use: 'The Vigil (meta hall)', wired: true },
  { id: 'roseWindow', title: 'Six Dark Panes', use: 'Vigil Rose Window tab', wired: true },
  { id: 'map', title: 'Lanterns on the Face of the Spire', use: 'Node-pick map (not reward/bossRelic)', wired: true },
  { id: 'safeNodes', title: 'Cold Goods, Warm Price', use: 'Shop, rest, treasure', wired: true },
  { id: 'act1Combat', title: 'Ashen Woods Scherzo', use: 'Act 1 normal fights', wired: true },
  { id: 'act1Boss', title: 'The Rootheart Awakens', use: 'Act 1 boss — Rootheart', wired: true },
  { id: 'act2Combat', title: 'Sunken City Waltz', use: 'Act 2 normal fights', wired: true },
  { id: 'act2Boss', title: "Leviathan's Maw", use: 'Act 2 boss — Leviathan', wired: true },
  { id: 'act3Combat', title: 'The Cracked Astral Court', use: 'Act 3 normal fights', wired: true },
  { id: 'act3Boss', title: 'The Eternal Sovereign', use: 'Act 3 boss — Eternal Sovereign', wired: true },
  { id: 'elite', title: 'Named Afflictions', use: 'Elite fights (all acts)', wired: true },
  { id: 'paleOnes', title: 'Witchlight Motes', use: 'Pale Ones quest combat', wired: true },
  { id: 'shadeDuel', title: 'The Duel That Remembers', use: 'Own Shade duel combat', wired: true },
  { id: 'usurper', title: 'Lantern With No Flame', use: 'Usurped Act 3 summit boss', wired: true },
  { id: 'eighthOmen', title: 'Broken Glyph Run', use: 'Eighth Omen act — map / non-boss combat', wired: true },
  { id: 'unreadablePage', title: 'It Reads Itself', use: 'Unreadable Page dawn reading', wired: true },
  { id: 'hollowLamplighter', title: 'The Unlit Way', use: 'Hollow Lamplighter meeting', wired: true },
  { id: 'sealedDoor', title: 'The Climb Continues', use: 'Sealed Act 4 door / act4Reveal dawn', wired: true },
  { id: 'victory', title: 'The Only Sunrise', use: 'Act 1/2 boss kill ceremony + final run victory / end(won)', wired: true },
  { id: 'defeat', title: 'A Mark in the Dark', use: 'Run defeat / end(!won)', wired: true },
];
