// Dev audio gallery catalog (?audio=1) — ids, where used, notes.
// Playback still goes through audio.js / music.js; this file is documentation only.

/** @type {{ id: string, group: string, use: string, note?: string, play?: 'sample'|'attack', attack?: { who: string, amount: number } }[]} */
export const SFX_CATALOG = [
  { id: 'click', group: 'UI', use: 'Buttons, menus, title actions', note: 'short click in the roguelite game with gothic theme' },
  { id: 'hover', group: 'UI', use: 'Card / option hover highlight', note: 'soft hover in the roguelite game with gothic theme' },
  { id: 'card', group: 'Cards', use: 'Card motion, toss, pile fidget' },
  { id: 'draw', group: 'Cards', use: 'Draw-to-hand (staggered per card)' },
  { id: 'atkHeroLight', group: 'Attack', use: 'Hero hit, light (amount+blocked ≤ 5)', play: 'attack', attack: { who: 'hero', amount: 3 } },
  { id: 'atkHeroMed', group: 'Attack', use: 'Hero hit, medium (6–15)', play: 'attack', attack: { who: 'hero', amount: 10 } },
  { id: 'atkHeroHeavy', group: 'Attack', use: 'Hero hit, heavy (≥ 16)', play: 'attack', attack: { who: 'hero', amount: 20 } },
  { id: 'atkEnemyLight', group: 'Attack', use: 'Enemy hit on player, light (≤ 5)', play: 'attack', attack: { who: 'enemy', amount: 3 } },
  { id: 'atkEnemyMed', group: 'Attack', use: 'Enemy hit on player, medium (6–15)', play: 'attack', attack: { who: 'enemy', amount: 10 } },
  { id: 'atkEnemyHeavy', group: 'Attack', use: 'Enemy hit on player, heavy (≥ 16)', play: 'attack', attack: { who: 'enemy', amount: 20 } },
  { id: 'slash', group: 'Attack (legacy)', use: 'Superseded by sfx.attack(); kept as sample / synth fallback', note: 'Legacy' },
  { id: 'hit', group: 'Attack (legacy)', use: 'Superseded by sfx.attack(); no-op wrapper now', note: 'Legacy' },
  { id: 'blocked', group: 'Combat', use: 'Damage absorbed by Ward / thorns ping / adamant hold', note: 'heavy blocked clang' },
  { id: 'block', group: 'Combat', use: 'Gain Ward', note: 'short gear-up' },
  { id: 'poison', group: 'Combat', use: 'Smolder / poison tick or apply', note: 'classic toxic hiss' },
  { id: 'debuff', group: 'Combat', use: 'Debuff apply, burn/self damage, some notices', note: 'short unpleasant downward' },
  { id: 'buff', group: 'Combat', use: 'Buff apply, power settle', note: 'short pleasant upward' },
  { id: 'heal', group: 'Combat', use: 'Heal / rest heal feedback' },
  { id: 'energy', group: 'Combat', use: 'Energy gain (sample ready; rarely called from UI)' },
  { id: 'coin', group: 'Meta', use: 'Gold pickup / shop coin fly' },
  { id: 'potion', group: 'Meta', use: 'Use / gain phial' },
  { id: 'death', group: 'Combat', use: 'Normal enemy death' },
  { id: 'bigDeath', group: 'Combat', use: 'Elite / boss death; also boss intro sting' },
  { id: 'turn', group: 'Combat', use: 'Your turn banner' },
  { id: 'victory', group: 'Combat', use: 'Fight won sting (SFX; BGM victory is separate)' },
  { id: 'defeat', group: 'Combat', use: 'Fight lost sting (SFX; BGM defeat is separate)' },
  { id: 'relic', group: 'Meta', use: 'Relic gain / lamplighter confirm' },
  { id: 'upgrade', group: 'Meta', use: 'Card upgrade at rest / forge' },
  { id: 'map', group: 'Meta', use: 'Map enter / node travel SFX (not BGM)' },
  { id: 'chip', group: 'SHATTER', use: 'Facet chip tick' },
  { id: 'shatter', group: 'SHATTER', use: 'Shatter burst' },
  { id: 'ember', group: 'SHATTER', use: 'Ember gain' },
  { id: 'kindle', group: 'SHATTER', use: 'Kindle / lantern feed' },
  { id: 'stagger', group: 'SHATTER', use: 'Enemy staggered' },
  { id: 'art', group: 'SHATTER', use: 'Lantern Art cast' },
  { id: 'omen', group: 'Meta', use: 'Omen banner / omen reveal' },
];

/** @type {{ id: string, title: string, use: string, wired: boolean }[]} */
export const MUSIC_CATALOG = [
  { id: 'title', title: 'Stained Glass Inscription', use: 'Title screen', wired: true },
  { id: 'embark', title: 'Light Your Lantern', use: 'Embark / Begin the Climb', wired: true },
  { id: 'vigil', title: 'Monuments in the Dark', use: 'The Vigil (meta hall)', wired: true },
  { id: 'roseWindow', title: 'Six Dark Panes', use: 'Emberglass / Rose Window (future)', wired: false },
  { id: 'map', title: 'Lanterns on the Face of the Spire', use: 'Node-pick map (not reward/bossRelic)', wired: true },
  { id: 'safeNodes', title: 'Cold Goods, Warm Price', use: 'Shop, rest, treasure', wired: true },
  { id: 'act1Combat', title: 'Ashen Woods Scherzo', use: 'Act 1 normal fights', wired: true },
  { id: 'act1Boss', title: 'The Rootheart Awakens', use: 'Act 1 boss — Rootheart', wired: true },
  { id: 'act2Combat', title: 'Sunken City Waltz', use: 'Act 2 normal fights', wired: true },
  { id: 'act2Boss', title: "Leviathan's Maw", use: 'Act 2 boss — Leviathan', wired: true },
  { id: 'act3Combat', title: 'The Cracked Astral Court', use: 'Act 3 normal fights', wired: true },
  { id: 'act3Boss', title: 'The Eternal Sovereign', use: 'Act 3 boss — Eternal Sovereign', wired: true },
  { id: 'elite', title: 'Named Afflictions', use: 'Elite fights (all acts)', wired: true },
  { id: 'paleOnes', title: 'Witchlight Motes', use: 'Hidden quest — Pale Ones (future)', wired: false },
  { id: 'shadeDuel', title: 'The Duel That Remembers', use: 'Hidden quest — shade duel (future)', wired: false },
  { id: 'usurper', title: 'Lantern With No Flame', use: 'Hidden quest — Usurper boss (future)', wired: false },
  { id: 'eighthOmen', title: 'Broken Glyph Run', use: 'Hidden quest — Eighth Omen run (future)', wired: false },
  { id: 'unreadablePage', title: 'It Reads Itself', use: 'Hidden quest — Unreadable Page (future)', wired: false },
  { id: 'hollowLamplighter', title: 'The Unlit Way', use: 'Hidden quest — hollow lamplighter (future)', wired: false },
  { id: 'sealedDoor', title: 'The Climb Continues', use: 'Sealed Act 4 door reveal (future)', wired: false },
  { id: 'victory', title: 'The Only Sunrise', use: 'Final run victory / end(won)', wired: true },
  { id: 'defeat', title: 'A Mark in the Dark', use: 'Run defeat / end(!won)', wired: true },
];
